# Site settings
title: RF24Remote
email: mzfuzzy800@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  RF24 is a set of libraries to enable using RF24 library remotely from another machine than nRF24l01 is connected to.
baseurl: "/RF24Remote/" # the subpath of your site, e.g. /blog/
url: "http://mz-fuzzy.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  mz-fuzzy

# Build settings
markdown: kramdown
kramdown:
  input: GFM

